digikala/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from store_app.views import IndexView
urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('store/', include('store_app.urls')),
    path('pay/', include('payment_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digikala/payment_app/urls.py
from re import template
from django.urls import path
from django.views.generic import TemplateView
from .views import ShoppingPaymentView, payment_compelete_view, payment_no_compelete_view, ShoppingView


app_name = 'payment_app'

urlpatterns = [
    path('shopping/payment/', ShoppingPaymentView.as_view(), name='shopping-payment'),
    path('shopping/payment/compelete/', payment_compelete_view, name='shopping-compelete'),
    path('shopping/payment/no/compelete/', payment_no_compelete_view, name='shopping-no-compelete'),
    path('shopping/', ShoppingView.as_view(), name="shopping")
]

digikala/store_app/urls.py
from django.urls import path
from .views import (ProductListView, MobileDetailView, CartListView, remove_from_cart,
                     ProductSearchView, LaptopDetailView)

app_name = 'store_app'

urlpatterns = [
    path('products/<slug:slug>/', ProductListView.as_view(), name='product-list'),
    path('product/phone/<int:pk>/', MobileDetailView.as_view(), name='mobile-detail'),
    path('product/laptop/<int:pk>/', LaptopDetailView.as_view(), name='laptop-detail'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('d/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('product/', ProductSearchView.as_view(), name='product-search'),

]

digikala/store_app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from multiselectfield import MultiSelectField
from ckeditor.fields import RichTextField


class Brand(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=30)
    slug = models.SlugField()

    def __str__(self):
        return self.title


class Product(models.Model):
    STORAGE_CHOICE = (
        ('16', '16'),
        ('32', '32'),
        ('64', '64'),
        ('128', '128'),
        ('256', '256'),
        ('512', '512'),
    )
    SIMCARD_CHOICE = (
        ('1', 'تک سیمکارت'),
        ('2', 'دو سیمکارت'),
        ('4', 'چهار سیمکارت'),
    )
    NETWORK_CHOICE = (
        ('2G', '2G'),
        ('3G', '3G'),
        ('4G', '4G'),
        ('5G', '5G'),
    )

    STORAGE_CHOICE = (
        
        ('128', '128 گیگ'),
        ('256', '256 گیگ'),
        ('512', '512 گیگ'),
        ('1024', '1 ترابایت'),
        ('2048', '2 ترابایت'),
    )
    PORT_NUMBER = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
    )
    RAM_CHOICE = (
        ('4', '4'),
        ('8', '8'),
        ('16', '16'),
        ('32', '32'),
    )

    persian_title = models.CharField(max_length=200)
    english_title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='store_app')
    weight = models.CharField(max_length=4, default='225') 
    price = models.PositiveIntegerField(default=12000000)
    review = RichTextField()
    created = models.DateTimeField(auto_now_add=True) # jalali date
    updated = models.DateTimeField(auto_now=True)
    brand = models.ForeignKey(Brand, models.CASCADE, related_name='mobiles')
    category = models.ForeignKey(Category, models.CASCADE, related_name='mobiles')
    count = models.PositiveSmallIntegerField(default=2)
    

    screen_size = models.CharField(max_length=10, default='15.6 اینچ', blank=True, null=True)
    usb_port_no = models.CharField(max_length=2, choices=PORT_NUMBER, default='3', blank=True, null=True)
    ram = models.CharField(max_length=3, choices=RAM_CHOICE, default='16', blank=True, null=True)
    proccessor_serie = models.CharField(max_length=20, default='Core i7', blank=True, null=True)    
    proccessor_builder = models.CharField(max_length=10, default='intel', blank=True, null=True)
    graphic_proccessor_builder = models.CharField(max_length=10, default='NVIDIA', blank=True, null=True)

    internal_storage = models.CharField(max_length=4, choices=STORAGE_CHOICE, default='256', blank=True, null=True)
    networks = MultiSelectField(choices=NETWORK_CHOICE, default=['2G','3G', '4G'], blank=True, null=True)
    pic_resolution = models.CharField(max_length=3, default='64')
    simcard_no = models.CharField(max_length=20, choices=SIMCARD_CHOICE, default='2', blank=True, null=True)
    special_features = models.TextField(blank=True, null=True)
    chipset = models.CharField(max_length=30, default='Apple A11 Bionic Chipset', blank=True, null=True)    
    chipset_type = models.CharField(max_length=3, default='64', blank=True, null=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.english_title

    # def get_absolute_url(self):
    #     return reverse('store_app:product-detail', kwargs={'pk': self.id})


class Comment(models.Model):
    STATUS = (
        ('d', 'Draft'),
        ('p', 'Publish')
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS, default='d')
    product = models.ForeignKey(Product, models.CASCADE)

    def __str__(self):
        return self.status


class Cart(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)

digikala/store_app/forms.py
from dataclasses import fields
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

digikala/store_app/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.shortcuts import redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Brand, Product, Comment, Cart, Product
from .forms import CommentForm
from .filters import ProductFilter


class ProductMixin:
    model = Product
    template_name = ''
    context_object_name = ''
    paginate_by = 4

    def querystring(self):
        qs = self.request.GET.copy()
        qs.pop(self.page_kwarg, None)
        return qs.urlencode()

    def get_queryset(self):
        if self.kwargs['slug'] == 'phone':
            qs = self.model.objects.filter(category__title='phone')
            return ProductFilter(self.request.GET, queryset=qs).qs
        elif self.kwargs['slug'] == 'laptop':
            qs = self.model.objects.filter(category__title='laptop')
            return ProductFilter(self.request.GET, queryset=qs).qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fltr'] = ProductFilter(self.request.GET, queryset=self.model.objects.all())
        context['ordr'] = self.request.GET
        context['brand'] = Brand.objects.all()
        return context
    

class ProductDetailMixin:
    model = Product
    template_name = ''
    context_object_name = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(status='p', product=Product.objects.get(pk=self.kwargs['pk']))
        return context

    def post(self, request, **kwargs):
        if 'message' in request.POST:
            form = CommentForm(request.POST)
            if form.is_valid():
                user = request.user
                message = form.cleaned_data['message']
                product = Product.objects.get(pk=self.kwargs['pk'])
                comment = Comment(user=user, message=message, product=product)
                comment.save()
            return redirect('store_app:mobile-detail', self.kwargs['pk'])
        else:
            if not request.user.is_authenticated:
                return redirect('accounts_app:login')
            product = Product.objects.get(id=self.kwargs['pk'])
            if Cart.objects.filter(product=product, user=request.user).exists():
                cart = Cart.objects.get(product=product, user=request.user)
                cart.quantity = cart.quantity + 1
                cart.save()
            else:
                Cart.objects.create(product=product, user=request.user)

            return redirect('store_app:cart')
        
    
class ProductListView(ProductMixin, ListView):
    template_name = 'store_app/product-list.html'
    context_object_name = 'filter'


class ProductSearchView(ProductMixin, ListView):
    template_name = 'store_app/search.html'
    context_object_name = 'products'

    def get_queryset(self):
        qry = self.request.GET.get('q')
        qs = self.model.objects.filter(Q(english_title__icontains=qry) | Q(persian_title__icontains=qry) | Q(review__icontains=qry))
        return ProductFilter(self.request.GET, queryset=qs).qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['ordr'] = self.request.GET
        context['qr'] = self.request.GET.get("q")
        return context
        
        
class MobileDetailView(ProductDetailMixin, DetailView):
    template_name = 'store_app/mobile-detail.html'
    context_object_name = 'mobile'


class LaptopDetailView(ProductDetailMixin, DetailView):
    template_name = 'store_app/laptop-detail.html'
    context_object_name = 'laptop'


class CartListView(LoginRequiredMixin, ListView):
    model = Cart
    template_name = 'store_app/cart.html'
    context_object_name = 'carts'

    def get_queryset(self):
        return Cart.objects.filter(user__email=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['totla_count'] = Cart.objects.filter(user__email=self.request.user).count()
        print(context)
        return context


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mobiles'] = Product.objects.filter(category__title='phone')[:7]
        context['laptops'] = Product.objects.filter(category__title='laptop')[:7]
        return context



def remove_from_cart(request, pk):
    cart = Cart.objects.get(id=pk)
    cart.delete()
    return HttpResponseRedirect(reverse('store_app:cart'))

digikala/templates/store_app/cart.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}

{% block title %} سبد خرید {% endblock %}

{% block content %}



        {% if carts %}
        <main class="cart-page default">
            <div class="container">
                <div class="row">
                    <div class="cart-page-content col-xl-9 col-lg-8 col-md-12 order-1">
                        <div class="cart-page-title">
                            <h1>سبد خرید</h1>
                        </div>
                        <div class="table-responsive checkout-content default">
                            {% for cart in carts %}
                            <table class="table">
                                <tbody>
                                    
                                    <tr class="checkout-item">
                                        <td>
                                            <img src="{{ cart.product.image.url }}" style="width:170px" alt="">
                                            <a href="{% url 'store_app:remove_from_cart' cart.pk %}" class="checkout-btn-remove"></a>
                                        </td>
                                        <td>
                                            <h3 class="checkout-title">
                                                {{ cart.product.persian_title }}
                                            </h3>
                                        </td>
                                        <td>{{ cart.quantity }} عدد</td>
                                        {% widthratio cart.product.price 1 cart.quantity as price %}
                                        <td> {{price|intcomma}} تومان</td>
                                    </tr>
                                   
                                </tbody>
                            </table>
                            {% endfor %}
                        </div>
                    </div>
                    <aside class="cart-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-2">
                        <div class="checkout-aside">
                            <div class="checkout-summary">
                                <div class="checkout-summary-main">
                                    <ul class="checkout-summary-summary">
                                        <li><span>مبلغ کل ({{totla_count}} کالا)</span><span>{{total_price|intcomma}} تومان</span></li>
                                        <li>
                                            <span>هزینه ارسال</span>
                                            <span>وابسته به آدرس<span class="wiki wiki-holder"><span
                                                        class="wiki-sign"></span>
                                                    <div class="wiki-container js-dk-wiki is-right">
                                                        <div class="wiki-arrow"></div>
                                                        <p class="wiki-text">
                                                            هزینه ارسال مرسولات می‌تواند وابسته به شهر و آدرس گیرنده
                                                            متفاوت باشد. در
                                                            صورتی که هر
                                                            یک از مرسولات حداقل ارزشی برابر با ۱۰۰هزار تومان داشته باشد،
                                                            آن مرسوله
                                                            بصورت رایگان
                                                            ارسال می‌شود.<br>
                                                            "حداقل ارزش هر مرسوله برای ارسال رایگان، می تواند متغیر
                                                            باشد."
                                                        </p>
                                                    </div>
                                                </span></span>
                                        </li>
                                    </ul>
                                    <div class="checkout-summary-devider">
                                        <div></div>
                                    </div>
                                    <div class="checkout-summary-content">
                                        <div class="checkout-summary-price-title">مبلغ قابل پرداخت:</div>
                                        <div class="checkout-summary-price-value">
                                            <span class="checkout-summary-price-value-amount">{{ total_price|intcomma }}</span> تومان
                                        </div>
                                        <a href="{% url 'payment_app:shopping' %}" class="selenium-next-step-shipping">
                                            <div class="parent-btn">
                                                <button class="dk-btn dk-btn-info">
                                                    ادامه ثبت سفارش
                                                    <i class="now-ui-icons shopping_basket"></i>
                                                </button>
                                            </div>
                                        </a>
                                        <div>
                                            <span>
                                                کالاهای موجود در سبد شما ثبت و رزرو نشده‌اند، برای ثبت سفارش مراحل بعدی
                                                را تکمیل
                                                کنید.
                                            </span>
                                            <span class="wiki wiki-holder"><span class="wiki-sign"></span>
                                                <div class="wiki-container is-right">
                                                    <div class="wiki-arrow"></div>
                                                    <p class="wiki-text">
                                                        محصولات موجود در سبد خرید شما تنها در صورت ثبت و پرداخت سفارش
                                                        برای شما رزرو
                                                        می‌شوند. در
                                                        صورت عدم ثبت سفارش، دیجی کالا هیچگونه مسئولیتی در قبال تغییر
                                                        قیمت یا موجودی
                                                        این کالاها
                                                        ندارد.
                                                    </p>
                                                </div>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="checkout-feature-aside">
                                <ul>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-guarantee">
                                        هفت روز
                                        ضمانت تعویض
                                    </li>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-cash">
                                        پرداخت در محل با
                                        کارت بانکی
                                    </li>
                                    <li class="checkout-feature-aside-item checkout-feature-aside-item-express">
                                        تحویل اکسپرس
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </aside>
                </div>
            </div>
        </main>
        {% else %}
        <main class="cart default">
            <div class="container text-center">
                <div class="cart-empty">
                    <div class="cart-empty-icon">
                        <i class="now-ui-icons shopping_basket"></i>
                    </div>
                    <div class="cart-empty-title">سبد خرید شما خالیست!</div>
                    {% if not user.is_authenticated %}
                    <div class="parent-btn">
                        <a href="#" class="dk-btn dk-btn-success">
                            به حساب کاربری خود وارد شوید
                            <i class="fa fa-sign-in"></i>
                        </a>
                    </div>
                    <div class="cart-empty-url">
                        <span>کاربر جدید هستید؟</span>
                        <a href="#">ثبت‌نام در دیجی کالا</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </main>
        {% endif %}
{% endblock %}

digikala/templates/store_app/product-brand-list.html
{% extends '_base.html' %}
{% load static %}
{% load humanize %}
{% load order %}

{% block title %} لیست محصولات {% endblock %}

{% block content %}

        <!-- main -->
        <main class="search-page default">
            <div class="container">
                <div class="row">
                    <aside class="sidebar-page col-12 col-sm-12 col-md-4 col-lg-3 order-1">
                        <form>
                            <div class="box">
                                <div class="box-header">
                                    <div class="box-toggle" data-toggle="collapse" href="#collapseExample1" role="button"
                                        aria-expanded="true" aria-controls="collapseExample1">
                                        محدوده قیمت
                                        <i class="now-ui-icons arrows-1_minimal-down"></i>
                                    </div>
                                </div>
                                <div class="box-content">
                                    <div class="collapse show" id="collapseExample1">
                                        <div style="text-align:center;" class="filter-option">
                                            
                                            <p><label>از</label>
                                            <input type='number' name='price__gt' min={{min_price}} max={{max_price}} value={{min_price}}
                                                style="text-align:center;width: 50%;padding: 6px 10px;margin: 8px 0;display: inline-block;border: 1px solid #ccc;border-radius: 4px;box-sizing: border-box;"> تومان </p>
                                            <p><label >تا</label>
                                            <input type='number' name='price__lt' min={{min_price}} max={{max_price}} value={{max_price}}
                                                style="text-align:center;width: 50%;padding: 6px 10px;margin: 8px 0;display: inline-block;border: 1px solid #ccc;border-radius: 4px;box-sizing: border-box;"> تومان </p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="box">
                                <div class="box-content">
                                    <input type="checkbox" name="ava" class="bootstrap-switch" {% if 'ava=on' in request.get_full_path %}checked{% endif %} />
                                    <label for="">فقط کالاهای موجود</label>
                                </div>
                            </div>

                            <div class="product-add default">
                                <div style="text-align:center;" class="parent-btn">
                                    <button type="submit" class="dk-btn dk-btn-info">
                                        اعمال فیلترها
                                    </button>
                                </div>
                            </div>

                        </form>
                    </aside>
                    <div class="col-12 col-sm-12 col-md-8 col-lg-9 order-2">
                        <div class="breadcrumb-section default">
                            <ul class="breadcrumb-list">
                                <li>
                                    <a href="#">
                                        <span>فروشگاه اینترنتی دیجی کالا</span>
                                    </a>
                                </li>
                                <li><span>جستجوی موبایل</span></li>
                            </ul>
                        </div>
                        <div class="listing default">
                            <div class="listing-counter">{{ view.get_queryset.count|intcomma }} کالا</div>
                            <div class="listing-header default">
                                <ul class="listing-sort nav nav-tabs justify-content-center" role="tablist"
                                    data-label="مرتب‌سازی بر اساس :">
                                    <li>
                                        <a href="{% url 'store_app:product-brand-list' brand %}{%if view.querystring %}?{% endif %}{% if 'ordering' in view.querystring %}{{ view.querystring|order }}{% else %}{{ view.querystring }}{% endif %}"
                                        {% if not ordr.ordering %} class="active" {% endif %}>مرتبط‌ترین</a>
                                    </li>
                                    
                                    <li>
                                        <a href="{% url 'store_app:product-brand-list' brand %}?ordering=desc&{% if 'ordering' in view.querystring %}{{ view.querystring|order }}{% else %}{{ view.querystring }}{% endif %}" 
                                        {% if ordr.ordering == 'desc' %}class="active" {% endif %}>جدیدترین</a>
                                    </li>
                                   
                                    <li>
                                        <a href="{% url 'store_app:product-brand-list' brand %}?ordering=price-l2h&{% if 'ordering' in view.querystring %}{{ view.querystring|order }}{% else %}{{ view.querystring }}{% endif %}" 
                                            {% if ordr.ordering == 'price-l2h' %} class="active" {% endif %}>ارزان‌ترین</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'store_app:product-brand-list' brand %}?ordering=price-h2l&{% if 'ordering' in view.querystring %}{{ view.querystring|order }}{% else %}{{ view.querystring }}{% endif %}" role="tab"
                                            {% if ordr.ordering == 'price-h2l' %} class="active" {% endif %} aria-expanded="false">گران‌ترین</a>
                                    </li>
                                </ul>
                            </div>

                            <div class="tab-content default text-center">
                                <div class="tab-pane active" id="related" role="tabpanel" aria-expanded="true">
                                    <div class="container no-padding-right">
                                        <ul class="row listing-items">


                                        {% for product in filter %}
                                            
                                            <li class="col-xl-3 col-lg-4 col-md-6 col-12 no-padding">
                                                <div class="product-box">
                                                    <div
                                                        class="product-seller-details product-seller-details-item-grid">
                                                        <span class="product-main-seller"><span
                                                                class="product-seller-details-label">فروشنده:
                                                            </span>دیجی کالا</span>
                                                        <span class="product-seller-details-badge-container"></span>
                                                    </div>
                                                    <a class="product-box-img" href="{{ product.get_absolute_url }}">
                                                        <img src="{{ product.image.url }}" alt="">
                                                    </a>
                                                    <div class="product-box-content">
                                                        <div class="product-box-content-row">
                                                            <div class="product-box-title">
                                                                <a href="#">
                                                                    {{ product.persian_title }}
                                                                </a>
                                                            </div>
                                                        </div>
                                                        <div class="product-box-row product-box-row-price">
                                                            <div class="price">
                                                                <div class="price-value">
                                                                    <div class="price-value-wrapper">
                                                                        {{ product.price|intcomma }} <span
                                                                            class="price-currency">تومان</span>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        
                                        {% empty %}

                                            <h1> هیچ محصولی یافت نشد. </h1>

                                        {% endfor %}


                                        </ul>
                                    </div>
                                </div>
                            </div>

                            {% if page_obj.has_other_pages %}

                            <div class="pager default text-center">
                                <ul class="pager-items">
                                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                                        <a class="page-link" href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}&{{ view.querystring }}{% endif %}"  aria-disabled="true">صفحه قبل</a>
                                      </li>
                                      {% for page in page_obj.paginator.page_range %}
                                    <li>
                                        <a class="pager-item {% if page_obj.number == page %} is-active {% endif %}" href="?page={{ page }}&{{ view.querystring }}">{{ page }}</a>
                                    </li>
                                    {% endfor %}
                                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                                        <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}&{{ view.querystring }}{% endif %}">صفحه بعد</a>
                                    </li>
                                </ul>
                            </div>
                            {% endif %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- main -->

{% endblock content %}