digikala/accounts_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from .views import RegisterView, WelcomeView, ProfileView, PassChangeView, ProfilePersonalInfoView, ProfileEditPersonalInfoView, ProfileOrderListView

app_name = 'accounts_app'

urlpatterns = [
    path('login/', auth_view.LoginView.as_view(template_name='accounts_app/login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('password/change/', PassChangeView.as_view(), name='password_change'),
    path('password/change/done/', 
        auth_view.PasswordChangeDoneView.as_view(template_name='accounts_app/password-change-done.html'), 
        name="password_change_done"),
    path('personal-info/', ProfilePersonalInfoView.as_view(), name='personal-info'),
    path('profile/checkout/<int:pk>/', ProfileEditPersonalInfoView.as_view(), name='edit-profile'),
    path('profile/order/', ProfileOrderListView.as_view(), name='profile-order'),

]

digikala/digikala/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from store_app.views import IndexView
urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts_app.urls')),
    path('store/', include('store_app.urls')),
    path('pay/', include('payment_app.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

digikala/store_app/urls.py
from django.urls import path
from .views import (ProductListView, MobileDetailView, CartListView, remove_from_cart,
                     ProductSearchView, LaptopDetailView)

app_name = 'store_app'

urlpatterns = [
    path('products/<slug:slug>/', ProductListView.as_view(), name='product-list'),
    path('product/phone/<int:pk>/', MobileDetailView.as_view(), name='mobile-detail'),
    path('product/laptop/<int:pk>/', LaptopDetailView.as_view(), name='laptop-detail'),
    path('cart/', CartListView.as_view(), name='cart'),
    path('d/<int:pk>/', remove_from_cart, name='remove_from_cart'),
    path('product/', ProductSearchView.as_view(), name='product-search'),

]

digikala/accounts_app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager ## A new class is imported. ##
from django.db import models
from django.utils.translation import gettext as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class Users(AbstractUser):
    username = None
    email = models.EmailField(unique=True)
    receiver_name = models.CharField(verbose_name='Reciever Name', null=True, blank=True, max_length=50)
    phone = models.CharField(max_length=11, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    post_id = models.CharField(max_length=10, null=True, blank=True)
    national_code = models.CharField(max_length=10, null=True, blank=True)
    newsletter = models.BooleanField(default=False, null=True, blank=True)
    card_number = models.CharField(max_length=16, null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()
    
    def __str__(self):
        return self.email

digikala/accounts_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _
from django.core.exceptions import ValidationError


message = {
    'required': 'لطفا فیلد گذرواژه را وارد کنید'
}

class UserCreatForm(UserCreationForm):
    error_messages = {
        'password_mismatch': "گذرواژه ها با هم تظابق ندارند",
    }
    password1 = forms.CharField(label='password', widget=forms.PasswordInput, error_messages=message)  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput, error_messages=message)  
    class Meta:
        model = get_user_model()
        fields = ('email', 'password1', 'password2')
        error_messages = {
            'email': {
                'required': 'لطفا فیلد ایمیل را وارد کنید',
                'invalid': 'ایمیل وارد شده معتبر نمیباشد',
                'unique': 'این ایمیل قبلا در سیستم ثبت شده است',
                },
        }


class UserPersonalInfoForm(forms.ModelForm):
    phone_error_message = {
        'max_length': 'شماره تلفن باید 11 رقم باشد',
        'min_length': 'شماره تلفن باید 11 رقم باشد',
    }
    post_error_message = {
        'max_length': 'کد پستی باید 10 رقم باشد',
        'min_length': 'کد پستی باید 10 رقم باشد',
    }
    national_code_error_message = {
        'max_length': 'کد ملی باید 10 رقم باشد',
        'min_length': 'کد ملی باید 10 رقم باشد',
    }
    card_number_error_message = {
        'max_length': 'شماره کارت باید 16 رقم باشد',
        'min_length': 'شماره کارت باید 16 رقم باشد',
    }
    phone = forms.CharField(error_messages=phone_error_message, max_length=11, min_length=11, required=False)
    post_id = forms.CharField(error_messages=post_error_message, max_length=10, min_length=10, required=False)
    national_code = forms.CharField(error_messages=national_code_error_message, max_length=10, min_length=10, required=False)
    card_number = forms.CharField(error_messages=card_number_error_message, max_length=16, min_length=16, required=False)
    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", "receiver_name", "phone", "address", "post_id", "national_code", "card_number", "newsletter")
        widgets = {
            'newsletter':forms.CheckboxInput(),
        }
       

    def clean_phone(self):
        phone = self.cleaned_data.get('phone', None)
        if phone:
            try:
                int(phone)
            except (ValueError, TypeError):
                raise ValidationError('شماره تلفنی که وارد کرده اید معتبر نمیباشد')
        return phone

    def clean_post_id(self):
        post_id = self.cleaned_data.get('post_id', None)
        if post_id:
            try:
                int(post_id)
            except (ValueError, TypeError):
                raise ValidationError('کد پستی که وارد کرده اید معتبر نمیباشد')
        return post_id

    def clean_national_code(self):
        national_code = self.cleaned_data['national_code']
        if national_code:
            try:
                int(national_code)
            except (ValueError, TypeError):
                raise ValidationError('کد ملی که وارد کرده اید معتبر نمیباشد')
        return national_code

    def clean_card_number(self):
        card_number = self.cleaned_data.get('card_number', None)
        if card_number:
            try:
                int(card_number)
            except (ValueError, TypeError):
                raise ValidationError('شماره کارتی که وارد کرده اید معتبر نمیباشد')
        return card_number

digikala/accounts_app/views.py
from django.views.generic import CreateView, TemplateView, UpdateView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.mixins import LoginRequiredMixin
from store_app.models import Cart
from .models import Users
from .forms import UserCreatForm, UserPersonalInfoForm


class RegisterView(CreateView):
    form_class = UserCreatForm
    success_url = reverse_lazy('accounts_app:welcome') # welcome
    template_name = 'accounts_app/register.html'


class WelcomeView(TemplateView):
    template_name = 'accounts_app/welcome.html'


class ProfileView(TemplateView):
    template_name = 'accounts_app/profile.html'


class PassChangeView(PasswordChangeView):
    template_name='accounts_app/password-change.html'
    success_url = reverse_lazy('accounts_app:password_change_done')


class ProfilePersonalInfoView(TemplateView):
    template_name = 'accounts_app/profile-personal-info.html'


class ProfileEditPersonalInfoView(LoginRequiredMixin, UpdateView):
    model = Users
    form_class = UserPersonalInfoForm
    success_url = reverse_lazy('accounts_app:profile')
    template_name = 'accounts_app/checkout.html'


class ProfileOrderListView(TemplateView):
    template_name = 'accounts_app/profile-orders.html'

digikala/templates/accounts_app/login.html
{% extends 'accounts_app/_accounts_base.html' %}
{% load static %}
{% block content %}

    <div class="wrapper default">
        <div class="container">
            <div class="row">
                <div class="main-content col-12 col-md-7 col-lg-5 mx-auto">
                    <div class="account-box">
                        <a href="#" class="logo">
                            <img src="assets/img/logo.png" alt="">
                        </a>
                        <div class="account-box-title text-right">ورود به دیجی کالا</div>
                        <div class="account-box-content">
                            <form method='post' class="form-account">
                                {% csrf_token %}
                                {% if form.errors %}
                                <p style='color:red'> نام کاربری یا رمز عبور اشتباه است </p>
                                {% endif %}
                                <div class="form-account-title">ایمیل</div>
                                <div class="form-account-row">
                                    <label class="input-label"><i class="now-ui-icons users_single-02"></i></label>
                                    <input name='username' class="input-field" type="email"
                                        placeholder="ایمیل خود را وارد نمایید">
                                </div>
                                <div class="form-account-title">رمز عبور
                                    <a href="mm" class="btn-link-border form-account-link">رمز
                                        عبور خود را فراموش
                                        کرده ام</a>
                                </div>
                                <div class="form-account-row">
                                    <label class="input-label"><i
                                            class="now-ui-icons ui-1_lock-circle-open"></i></label>
                                    <input name='password' class="input-field" type="password"
                                        placeholder="رمز عبور خود را وارد نمایید">
                                </div>
                                <div class="form-account-row form-account-submit">
                                    <div class="parent-btn">
                                        <button class="dk-btn dk-btn-info">
                                            ورود به دیجی کالا
                                            <i class="fa fa-sign-in"></i>
                                        </button>
                                    </div>
                                </div>
                                <div class="form-account-agree">
                                    <label class="checkbox-form checkbox-primary">
                                        <input type="checkbox" checked="checked" id="agree">
                                        <span class="checkbox-check"></span>
                                    </label>
                                    <label for="agree">مرا به خاطر داشته باش</label>
                                </div>
                            </form>
                        </div>
                        <div class="account-box-footer">
                            <span>کاربر جدید هستید؟</span>
                            <a href="{% url 'accounts_app:register' %}" class="btn-link-border">ثبت‌نام در
                                دیجی کالا</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="mini-footer">
            <nav>
                <div class="container">
                    <ul class="menu">
                        <li>
                            <a href="#">درباره دیجی کالا</a>
                        </li>
                        <li>
                            <a href="#">فرصت‌های شغلی</a>
                        </li>
                        <li>
                            <a href="#">تماس با ما</a>
                        </li>
                        <li>
                            <a href="#">همکاری با سازمان‌ها</a>
                        </li>

                    </ul>
                </div>
            </nav>
            <div class="copyright-bar">
                <div class="container">
                    <p>
                        استفاده از مطالب فروشگاه اینترنتی دیجی کالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                        کلیه حقوق این سایت متعلق
                        به شرکت نوآوران فن آوازه (فروشگاه آنلاین دیجی کالا) می‌باشد.
                    </p>
                </div>
            </div>
        </footer>
    </div>

{% endblock %}

digikala/templates/accounts_app/profile-orders.html
{% extends '_base.html' %}
{% load static %}

{% block title %}
    لیست سفارشات
{% endblock title %}

{% block content %}
        <!-- main -->
        <main class="profile-user-page default">
            <div class="container">
                <div class="row">
                    <div class="profile-page col-xl-9 col-lg-8 col-md-12 order-2">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-12">
                                    <h1 class="title-tab-content">همه سفارش ها</h1>
                                </div>
                                <div class="content-section default">
                                    <div class="row">
                                        {% for cart in carts %}
                                        <div class="col-md-6 col-sm-12">
                                            <div class="profile-recent-fav-row">
                                                <a href="{% if cart.product.category.title == 'phone' %}{% url 'store_app:mobile-detail' cart.product.pk %}{% elif cart.product.category.title == 'laptop' %}{% url 'store_app:laptop-detail' cart.product.pk %}{% endif %}" class="profile-recent-fav-col profile-recent-fav-col-thumb">
                                                    <img src="{{ cart.product.image.url }}"></a>
                                                <div class="profile-recent-fav-col profile-recent-fav-col-title">
                                                    <a href="{% if cart.product.category.title == 'phone' %}{% url 'store_app:mobile-detail' cart.product.pk %}{% elif cart.product.category.title == 'laptop' %}{% url 'store_app:laptop-detail' cart.product.pk %}{% endif %}">
                                                        <h4 class="profile-recent-fav-name">
                                                            {{ cart.product.persian_title }}
                                                        </h4>
                                                    </a>
                                                    <div class="profile-recent-fav-price">{{ cart.product.price }} تومان</div>
                                                </div>
                                                <div class="profile-recent-fav-col profile-recent-fav-col-actions">
                                                    <a href="{% url 'store_app:remove_from_cart' cart.id %}">
                                                        <button class="btn-action btn-action-remove">
                                                            <i class="fa fa-trash"></i>
                                                        </button>
                                                    </a>
                                                </div>
                                                <div class="col-12 text-left mb-3">
                                                    <a href="{% if cart.product.category.title == 'phone' %}{% url 'store_app:mobile-detail' cart.product.pk %}{% elif cart.product.category.title == 'laptop' %}{% url 'store_app:laptop-detail' cart.product.pk %}{% endif %}" class="view-product">مشاهده محصول</a>
                                                </div>
                                            </div>
                                        </div>
                                        {% empty %}
                                        <div class="col-12 text-center">
                                            <div class="content-section pt-5 pb-5">
                                                <div class="icon-empty">
                                                    <i class="now-ui-icons travel_info"></i>
                                                </div>
                                                <h1 class="text-empty">موردی برای نمایش وجود ندارد!</h1>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="profile-page-aside col-xl-3 col-lg-4 col-md-6 center-section order-1">
                        <div class="profile-box">
                            <div class="profile-box-header">
                                <div class="profile-box-avatar">
                                    <img src="{% static 'img/svg/user.svg' %}" alt="">
                                </div>
                                <button data-toggle="modal" data-target="#myModal" class="profile-box-btn-edit">
                                    <i class="fa fa-pencil"></i>
                                </button>
                                <!-- Modal Core -->
                                <div class="modal-share modal-width-custom modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                                                <h4 class="modal-title" id="myModalLabel">تغییر نمایه کاربری شما</h4>
                                            </div>
                                            <div class="modal-body">
                                                <ul class="profile-avatars default text-center">
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/user.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-1.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-2.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-3.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-4.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-5.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-6.svg' %}"></img>
                                                    </li>
                                                    <li>
                                                        <img class="profile-avatars-item" src="{% static 'img/svg/avatar-7.svg' %}"></img>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- Modal Core -->
                            </div>
                            <div class="profile-box-username">{% if user.last_name or user.first_name %}
                                {{user.first_name}} {{user.last_name}}
                                {% endif %} </div>
                                <div class="profile-box-tabs">
                                    <a href="{% url 'accounts_app:password_change' %}" class="profile-box-tab profile-box-tab-access">
                                        <i class="now-ui-icons ui-1_lock-circle-open"></i>
                                        تغییر رمز
                                    </a>
                                    <a href="{% url 'accounts_app:logout' %}" class="profile-box-tab profile-box-tab--sign-out">
                                        <i class="now-ui-icons media-1_button-power"></i>
                                        خروج از حساب
                                    </a>
                                </div>
                        </div>
                        <div class="responsive-profile-menu show-md">
                            <div class="btn-group">
                                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-navicon"></i>
                                    حساب کاربری شما
                                </button>
                                <div class="dropdown-menu dropdown-menu-right text-right">
                                    <a href="profile.html" class="dropdown-item">
                                    <i class="now-ui-icons users_single-02"></i>
                                    پروفایل
                                    </a>
                                    <a href="profile-orders.html" class="dropdown-item active-menu">
                                    <i class="now-ui-icons shopping_basket"></i>
                                    همه سفارش ها
                                    </a>
                                    <a href="profile-orders-return.html" class="dropdown-item">
                                    <i class="now-ui-icons files_single-copy-04"></i>
                                    درخواست مرجوعی
                                    </a>
                                    <a href="profile-favorites.html" class="dropdown-item">
                                    <i class="now-ui-icons ui-2_favourite-28"></i>
                                    لیست علاقمندی ها
                                    </a>
                                    <a href="profile-personal-info.html" class="dropdown-item">
                                    <i class="now-ui-icons business_badge"></i>
                                    اطلاعات شخصی
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="profile-menu hidden-md">
                            <div class="profile-menu-header">حساب کاربری شما</div>
                            <ul class="profile-menu-items">
                                <li>
                                    <a href="{% url 'accounts_app:profile' %}">
                                        <i class="now-ui-icons users_single-02"></i>
                                        پروفایل
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'accounts_app:profile-order' %}" class="active">
                                        <i class="now-ui-icons shopping_basket"></i>
                                        همه سفارش ها
                                    </a>
                                </li>
                                <li>
                                    <a href="{% url 'accounts_app:personal-info' %}">
                                        <i class="now-ui-icons business_badge"></i>
                                        اطلاعات شخصی
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- main -->

{% endblock %}

digikala/templates/accounts_app/welcome.html
{% extends 'accounts_app/_accounts_base.html' %}
{% load static %}
{% block content %}

    <div class="wrapper default">
        <div class="container">
            <div class="row">
                <div class="main-content col-12 col-md-7 col-lg-5 mx-auto">
                    <div class="account-box text-center">
                        <a href="#" class="logo">
                            <img src="assets/img/logo.png" alt="">
                        </a>
                        <div class="account-box-title text-center">به دیجی کالا خوش آمدید</div>
                        <div class="account-box-content">
                            <div class="account-box-message">
                                <i class="account-box-message-icon now-ui-icons users_single-02"></i>
                                <h3>حساب کاربری شما در دیجی کالا ساخته شد</h3>
                                <p>اکنون می‌توانید به صفحه‌ای که در آن بودید بازگردید و یا با تکمیل اطلاعات حساب کاربری
                                    خود به کلیه امکانات و
                                    سرویس‌های دیجی کالا و سرویس‌های وابسته به آن دسترسی داشته باشید</p>
                                <ul class="account-box-message-links">
                                    <li>
                                        <div class="parent-btn">
                                            <a href="#" class="dk-btn dk-btn-info">
                                                تکمیل حساب کاربری
                                                <i class="now-ui-icons users_single-02"></i>
                                            </a>
                                        </div>
                                    </li>
                                    <li><a href="{% url 'accounts_app:login' %}" class="btn-link-border">بازگشت به صفحه‌ای که در آن بودید</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="mini-footer">
            <nav>
                <div class="container">
                    <ul class="menu">
                        <li>
                            <a href="#">درباره دیجی کالا</a>
                        </li>
                        <li>
                            <a href="#">فرصت‌های شغلی</a>
                        </li>
                        <li>
                            <a href="#">تماس با ما</a>
                        </li>
                        <li>
                            <a href="#">همکاری با سازمان‌ها</a>
                        </li>

                    </ul>
                </div>
            </nav>
            <div class="copyright-bar">
                <div class="container">
                    <p>
                        استفاده از مطالب فروشگاه اینترنتی دیجی کالا فقط برای مقاصد غیرتجاری و با ذکر منبع بلامانع است.
                        کلیه حقوق این سایت متعلق
                        به شرکت نوآوران فن آوازه (فروشگاه آنلاین دیجی کالا) می‌باشد.
                    </p>
                </div>
            </div>
        </footer>
    </div>
{% endblock %}